packages:
  - apps/*
  - packages/*

overrides:
  adm-zip: 0.6.0
  serialize-javascript: 7.1.0
  tmp: 0.2.7
  undici@<6.27.0: 6.27.0
  ws: 8.21.3

allowBuilds:
  esbuild: true
  keccak: true
  secp256k1: true
  unrs-resolver: true

minimumReleaseAgeExclude:
  - "@next/env@16.3.1"
  - "@next/eslint-plugin-next@16.3.1"
  - "@next/swc-darwin-arm64@16.3.1"
  - "@next/swc-darwin-x64@16.3.1"
  - "@next/swc-linux-arm64-gnu@16.3.1"
  - "@next/swc-linux-arm64-musl@16.3.1"
  - "@next/swc-linux-x64-gnu@16.3.1"
  - "@next/swc-linux-x64-musl@16.3.1"
  - "@next/swc-win32-arm64-msvc@16.3.1"
  - "@next/swc-win32-x64-msvc@16.3.1"
  - eslint-config-next@16.3.1
  - next@16.3.1

onlyBuiltDependencies:
  - sharp
  - unrs-resolver
